services:
  db:
      container_name: keycloak-test_db
      image: postgres:latest
      # restart: unless-stopped # Always restart the container if it stops unless stopped manually
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD:  ${POSTGRES_PASS}
      ports:
        - "${POSTGRES_DB_PORT}:5432" # Map port 5432 of the container to port 5432 on the host
      volumes:
        - ./.db:/var/lib/postgresql/data
      networks:
        - keycloak_network
  keycloak:
    container_name: keycloak-test
    image: quay.io/keycloak/keycloak:23.0.6
    command: start
    # restart: always
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://host.docker.internal:5433/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASS}
    ports: 
      - ${KEYCLOAK_PORT}:8080
    networks:
        - keycloak_network
    depends_on:
      - db

networks:
  keycloak_network:
    driver: bridge